name: Build

on:
  workflow_call:
    inputs:
      project-id:
        required: true
        type: string
    # secrets: inherit
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create env file
      run: |
        touch .env
        echo FB_PROJECT_ID=${{ inputs.project-id }} >> .env
        cat .env
    - name: Use Node.js ${{ vars.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ vars.NODE_VERSION }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test --if-present
