# A reusable workflow for deployments

name: Deploy

on:
  workflow_call:
    inputs:
      project-id:
        required: true
        type: string
      firebase-service-account:
        required: true
        type: string
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # BEGIN BUILD AND TEST
      - uses: actions/checkout@v3
      - name: Create env file for ${{ inputs.project-id }}
        run: |
          touch .env
          echo FB_PROJECT_ID=${{ inputs.project-id }} >> .env
          cat .env
      - name: Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npm test
      # END BUILD AND TEST
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ inputs.firebase-service-account }}'
          projectId: ${{ inputs.project-id }}
