# Deploys production websites on push to master

name: Deploy Production

on:
  push:
    branches:
      - 'master'
  
jobs:
  deploy_prod:    
    strategy:
      matrix:
        include:          
          - projectId: "larisahorback-prod"
            firebaseServiceAccount: FIREBASE_SERVICE_ACCOUNT_LARISAHORBACK_PROD
          # - projectId: "habor-dev"
          #  firebaseServiceAccount: FIREBASE_SERVICE_ACCOUNT_HABOR_DEV
    runs-on: ubuntu-latest
    steps:
      # BEGIN BUILD AND TEST
      - uses: actions/checkout@v3
      - name: Create env file for ${{ matrix.projectId }}
        run: |
          touch .env
          echo FB_PROJECT_ID=${{ matrix.projectId }} >> .env
          cat .env
      - name: Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npm test
      # END BUILD AND TEST
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets[matrix.firebaseServiceAccount] }}'
          channelId: live
          projectId: '${{ matrix.projectId }}'